// <auto-generated />
using System;
using Collectary.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Collectary.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260601221542_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("Collectary.Core.Domain.FieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentListFieldDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PresetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentListFieldDefinitionId");

                    b.HasIndex("PresetId");

                    b.ToTable("FieldDefinitions", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Collectary.Core.Domain.FieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ListEntryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ListEntryId");

                    b.ToTable("FieldValues", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PresetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.ListEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ListFieldValueId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListFieldValueId");

                    b.ToTable("ListEntries", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Preset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentPresetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentPresetId");

                    b.ToTable("Presets", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.BoolFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("BoolFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ColorFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("ColorFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DateFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<DateTime?>("Max")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Min")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("DateFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DecimalFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("DecimalFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DisplayNameFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("DisplayNameFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ImageFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.ToTable("ImageFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.IntegerFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<int?>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("IntegerFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ListFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<int>("InlineStyle")
                        .HasColumnType("INTEGER");

                    b.ToTable("ListFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.MultiChoiceFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("MultiChoiceFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.RatingFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<int>("MaxStars")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("RatingFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.SingleChoiceFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("SingleChoiceFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.TextFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("TextFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.UrlFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("UrlFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.BoolFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<bool?>("Value")
                        .HasColumnType("INTEGER");

                    b.ToTable("BoolFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ColorFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.ToTable("ColorFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DateFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<DateTime?>("Value")
                        .HasColumnType("TEXT");

                    b.ToTable("DateFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DecimalFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<decimal?>("Value")
                        .HasColumnType("TEXT");

                    b.ToTable("DecimalFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ImageFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("ImageKey")
                        .HasColumnType("TEXT");

                    b.ToTable("ImageFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.IntegerFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<int?>("Value")
                        .HasColumnType("INTEGER");

                    b.ToTable("IntegerFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ListFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.ToTable("ListFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.MultiChoiceFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("Selected")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("MultiChoiceFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.RatingFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<int?>("Stars")
                        .HasColumnType("INTEGER");

                    b.ToTable("RatingFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.SingleChoiceFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("Selected")
                        .HasColumnType("TEXT");

                    b.ToTable("SingleChoiceFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.TextFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.ToTable("TextFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.UrlFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.ToTable("UrlFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.FieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.Fields.ListFieldDefinition", null)
                        .WithMany("SubFields")
                        .HasForeignKey("ParentListFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Collectary.Core.Domain.Preset", null)
                        .WithMany("Fields")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Collectary.Core.Domain.FieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithMany()
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collectary.Core.Domain.Item", null)
                        .WithMany("Values")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Collectary.Core.Domain.ListEntry", null)
                        .WithMany("SubValues")
                        .HasForeignKey("ListEntryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Collectary.Core.Domain.ListEntry", b =>
                {
                    b.HasOne("Collectary.Core.Domain.Fields.ListFieldValue", null)
                        .WithMany("Entries")
                        .HasForeignKey("ListFieldValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Preset", b =>
                {
                    b.HasOne("Collectary.Core.Domain.Preset", null)
                        .WithMany()
                        .HasForeignKey("ParentPresetId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.BoolFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.BoolFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ColorFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.ColorFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DateFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.DateFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DecimalFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.DecimalFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DisplayNameFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.DisplayNameFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ImageFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.ImageFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.IntegerFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.IntegerFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ListFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.ListFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.MultiChoiceFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.MultiChoiceFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Collectary.Core.Domain.Fields.ChoiceOption", "Choices", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("MultiChoiceFieldDefinitionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("MultiChoiceFieldDefinitionId");

                            b1.ToTable("MultiChoiceOptions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MultiChoiceFieldDefinitionId");
                        });

                    b.Navigation("Choices");
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.RatingFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.RatingFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.SingleChoiceFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.SingleChoiceFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Collectary.Core.Domain.Fields.ChoiceOption", "Choices", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("SingleChoiceFieldDefinitionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("SingleChoiceFieldDefinitionId");

                            b1.ToTable("SingleChoiceOptions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SingleChoiceFieldDefinitionId");
                        });

                    b.Navigation("Choices");
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.TextFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.TextFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.UrlFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.UrlFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.BoolFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.BoolFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ColorFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.ColorFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DateFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.DateFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DecimalFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.DecimalFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ImageFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.ImageFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.IntegerFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.IntegerFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ListFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.ListFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.MultiChoiceFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.MultiChoiceFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.RatingFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.RatingFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.SingleChoiceFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.SingleChoiceFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.TextFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.TextFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.UrlFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.UrlFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Item", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Collectary.Core.Domain.ListEntry", b =>
                {
                    b.Navigation("SubValues");
                });

            modelBuilder.Entity("Collectary.Core.Domain.Preset", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ListFieldDefinition", b =>
                {
                    b.Navigation("SubFields");
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ListFieldValue", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
