// <auto-generated />
using System;
using Collectary.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Collectary.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260606025435_RenameSystemFieldsToSharedFields")]
    partial class RenameSystemFieldsToSharedFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("Collectary.Core.Domain.CollectionShare", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Permission")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PresetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SharedWithUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PresetId", "SharedWithUserId")
                        .IsUnique();

                    b.ToTable("CollectionShares", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.FieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ColumnSpan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentListFieldDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PresetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SharedFieldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentListFieldDefinitionId");

                    b.HasIndex("PresetId");

                    b.HasIndex("SharedFieldId")
                        .IsUnique();

                    b.ToTable("FieldDefinitions", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Collectary.Core.Domain.FieldGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ColumnCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DefaultCollapsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentListFieldDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PrefixColumnHeaders")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PresetId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.HasIndex("ParentListFieldDefinitionId");

                    b.HasIndex("PresetId");

                    b.ToTable("FieldGroups", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.FieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ListEntryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ListEntryId");

                    b.ToTable("FieldValues", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("BaseRevision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDirty")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PresetId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.ListEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ListFieldValueId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListFieldValueId");

                    b.ToTable("ListEntries", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.ListSharedField", b =>
                {
                    b.Property<Guid>("ListFieldDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SharedFieldId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("ListFieldDefinitionId", "SharedFieldId");

                    b.HasIndex("SharedFieldId");

                    b.ToTable("ListSharedFields", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Preset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("BaseRevision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColumnCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FieldLabelLayout")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDirty")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentPresetId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentPresetId");

                    b.ToTable("Presets", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.PresetSharedField", b =>
                {
                    b.Property<Guid>("PresetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SharedFieldId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("PresetId", "SharedFieldId");

                    b.HasIndex("SharedFieldId");

                    b.ToTable("PresetSharedFields", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.SharedField", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("BaseRevision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDirty")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SharedFields", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Collectary.Infrastructure.Persistence.UserCredentialRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Iterations")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("UserId");

                    b.ToTable("UserCredentials", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.AudioFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.ToTable("AudioFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.BarcodeFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("BarcodeFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.BoolFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("BoolFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ColorFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("ColorFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.CountryFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("CountryFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.CurrencyFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("CurrencyFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DateFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<DateTime?>("Max")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Min")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("DateFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DateRangeFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("DateRangeFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DecimalFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("DecimalFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DisplayNameFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("DisplayNameFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DurationFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("DurationFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.EmailFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("EmailFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.FileAttachmentFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.ToTable("FileAttachmentFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ImageFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<int>("DisplayHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeMode")
                        .HasColumnType("INTEGER");

                    b.ToTable("ImageFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.IntegerFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<int?>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("IntegerFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.LinkedItemFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("LinkedItemFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ListFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<int>("ColumnCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InlineStyle")
                        .HasColumnType("INTEGER");

                    b.ToTable("ListFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.MeasurementFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("MeasurementFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.MultiChoiceFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("MultiChoiceFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.MultiImageFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.ToTable("MultiImageFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.PercentageFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("PercentageFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.PhoneFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("PhoneFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ProgressFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("ProgressFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.QrCodeFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("QrCodeFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.RatingFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<int>("MaxStars")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("RatingFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.RichTextFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("RichTextFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.SingleChoiceFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("SingleChoiceFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.SliderFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("SliderFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.TagsFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("TagsFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.TextFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("TextFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.TimeFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("TimeFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.UrlFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("UrlFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.WeightFieldDefinition", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldDefinition");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER");

                    b.ToTable("WeightFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.AudioFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("AudioKey")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.ToTable("AudioFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.BarcodeFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<int>("Symbology")
                        .HasColumnType("INTEGER");

                    b.ToTable("BarcodeFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.BoolFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<bool?>("Value")
                        .HasColumnType("INTEGER");

                    b.ToTable("BoolFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ColorFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.ToTable("ColorFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.CountryFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.ToTable("CountryFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.CurrencyFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<decimal?>("Value")
                        .HasColumnType("TEXT");

                    b.ToTable("CurrencyFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DateFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<DateTime?>("Value")
                        .HasColumnType("TEXT");

                    b.ToTable("DateFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DateRangeFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<DateTime?>("From")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("To")
                        .HasColumnType("TEXT");

                    b.ToTable("DateRangeFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DecimalFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<decimal?>("Value")
                        .HasColumnType("TEXT");

                    b.ToTable("DecimalFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DurationFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<int?>("TotalMinutes")
                        .HasColumnType("INTEGER");

                    b.ToTable("DurationFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.EmailFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.ToTable("EmailFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.FileAttachmentFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.ToTable("FileAttachmentFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ImageFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageKey")
                        .HasColumnType("TEXT");

                    b.ToTable("ImageFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.IntegerFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<int?>("Value")
                        .HasColumnType("INTEGER");

                    b.ToTable("IntegerFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.LinkedItemFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("TargetDisplay")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetItemId")
                        .HasColumnType("TEXT");

                    b.ToTable("LinkedItemFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ListFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.ToTable("ListFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.MeasurementFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("MeasurementFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.MultiChoiceFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("Selected")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("MultiChoiceFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.MultiImageFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("ImageKeys")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("MultiImageFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.PercentageFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<decimal?>("Value")
                        .HasColumnType("TEXT");

                    b.ToTable("PercentageFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.PhoneFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.ToTable("PhoneFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ProgressFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<int?>("Have")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Total")
                        .HasColumnType("INTEGER");

                    b.ToTable("ProgressFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.QrCodeFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.ToTable("QrCodeFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.RatingFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<int?>("Stars")
                        .HasColumnType("INTEGER");

                    b.ToTable("RatingFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.RichTextFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.ToTable("RichTextFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.SingleChoiceFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("Selected")
                        .HasColumnType("TEXT");

                    b.ToTable("SingleChoiceFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.SliderFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<int?>("Value")
                        .HasColumnType("INTEGER");

                    b.ToTable("SliderFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.TagsFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("TagsFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.TextFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.ToTable("TextFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.TimeFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.ToTable("TimeFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.UrlFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.ToTable("UrlFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.WeightFieldValue", b =>
                {
                    b.HasBaseType("Collectary.Core.Domain.FieldValue");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("WeightFieldValues", (string)null);
                });

            modelBuilder.Entity("Collectary.Core.Domain.FieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.Fields.ListFieldDefinition", null)
                        .WithMany("SubFields")
                        .HasForeignKey("ParentListFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Collectary.Core.Domain.Preset", null)
                        .WithMany("Fields")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Collectary.Core.Domain.SharedField", null)
                        .WithOne("Definition")
                        .HasForeignKey("Collectary.Core.Domain.FieldDefinition", "SharedFieldId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Collectary.Core.Domain.FieldGroup", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldGroup", null)
                        .WithMany()
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Collectary.Core.Domain.Fields.ListFieldDefinition", null)
                        .WithMany("Groups")
                        .HasForeignKey("ParentListFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Collectary.Core.Domain.Preset", null)
                        .WithMany("Groups")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Collectary.Core.Domain.FieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithMany()
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collectary.Core.Domain.Item", null)
                        .WithMany("Values")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Collectary.Core.Domain.ListEntry", null)
                        .WithMany("SubValues")
                        .HasForeignKey("ListEntryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Collectary.Core.Domain.ListEntry", b =>
                {
                    b.HasOne("Collectary.Core.Domain.Fields.ListFieldValue", null)
                        .WithMany("Entries")
                        .HasForeignKey("ListFieldValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.ListSharedField", b =>
                {
                    b.HasOne("Collectary.Core.Domain.Fields.ListFieldDefinition", null)
                        .WithMany("SharedFieldRefs")
                        .HasForeignKey("ListFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collectary.Core.Domain.SharedField", "SharedField")
                        .WithMany()
                        .HasForeignKey("SharedFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SharedField");
                });

            modelBuilder.Entity("Collectary.Core.Domain.Preset", b =>
                {
                    b.HasOne("Collectary.Core.Domain.Preset", null)
                        .WithMany()
                        .HasForeignKey("ParentPresetId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Collectary.Core.Domain.PresetSharedField", b =>
                {
                    b.HasOne("Collectary.Core.Domain.Preset", null)
                        .WithMany("SharedFieldRefs")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collectary.Core.Domain.SharedField", "SharedField")
                        .WithMany()
                        .HasForeignKey("SharedFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SharedField");
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.AudioFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.AudioFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.BarcodeFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.BarcodeFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.BoolFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.BoolFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ColorFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.ColorFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.CountryFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.CountryFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.CurrencyFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.CurrencyFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DateFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.DateFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DateRangeFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.DateRangeFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DecimalFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.DecimalFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DisplayNameFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.DisplayNameFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DurationFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.DurationFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.EmailFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.EmailFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.FileAttachmentFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.FileAttachmentFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ImageFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.ImageFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.IntegerFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.IntegerFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.LinkedItemFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.LinkedItemFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ListFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.ListFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.MeasurementFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.MeasurementFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.MultiChoiceFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.MultiChoiceFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Collectary.Core.Domain.Fields.ChoiceOption", "Choices", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("MultiChoiceFieldDefinitionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("MultiChoiceFieldDefinitionId");

                            b1.ToTable("MultiChoiceOptions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MultiChoiceFieldDefinitionId");
                        });

                    b.Navigation("Choices");
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.MultiImageFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.MultiImageFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.PercentageFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.PercentageFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.PhoneFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.PhoneFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ProgressFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.ProgressFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.QrCodeFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.QrCodeFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.RatingFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.RatingFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.RichTextFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.RichTextFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.SingleChoiceFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.SingleChoiceFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Collectary.Core.Domain.Fields.ChoiceOption", "Choices", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("SingleChoiceFieldDefinitionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("SingleChoiceFieldDefinitionId");

                            b1.ToTable("SingleChoiceOptions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SingleChoiceFieldDefinitionId");
                        });

                    b.Navigation("Choices");
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.SliderFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.SliderFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.TagsFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.TagsFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.TextFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.TextFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.TimeFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.TimeFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.UrlFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.UrlFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.WeightFieldDefinition", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldDefinition", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.WeightFieldDefinition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.AudioFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.AudioFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.BarcodeFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.BarcodeFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.BoolFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.BoolFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ColorFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.ColorFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.CountryFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.CountryFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.CurrencyFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.CurrencyFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DateFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.DateFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DateRangeFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.DateRangeFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DecimalFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.DecimalFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.DurationFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.DurationFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.EmailFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.EmailFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.FileAttachmentFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.FileAttachmentFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Collectary.Core.Domain.Fields.FileAttachment", "Files", b1 =>
                        {
                            b1.Property<Guid>("OwnerValueId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Key")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("OwnerValueId", "Key");

                            b1.ToTable("FileAttachmentEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OwnerValueId");
                        });

                    b.Navigation("Files");
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ImageFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.ImageFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.IntegerFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.IntegerFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.LinkedItemFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.LinkedItemFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ListFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.ListFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.MeasurementFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.MeasurementFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.MultiChoiceFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.MultiChoiceFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.MultiImageFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.MultiImageFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.PercentageFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.PercentageFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.PhoneFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.PhoneFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ProgressFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.ProgressFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.QrCodeFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.QrCodeFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.RatingFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.RatingFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.RichTextFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.RichTextFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.SingleChoiceFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.SingleChoiceFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.SliderFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.SliderFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.TagsFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.TagsFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.TextFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.TextFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.TimeFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.TimeFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.UrlFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.UrlFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.WeightFieldValue", b =>
                {
                    b.HasOne("Collectary.Core.Domain.FieldValue", null)
                        .WithOne()
                        .HasForeignKey("Collectary.Core.Domain.Fields.WeightFieldValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Item", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Collectary.Core.Domain.ListEntry", b =>
                {
                    b.Navigation("SubValues");
                });

            modelBuilder.Entity("Collectary.Core.Domain.Preset", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Groups");

                    b.Navigation("SharedFieldRefs");
                });

            modelBuilder.Entity("Collectary.Core.Domain.SharedField", b =>
                {
                    b.Navigation("Definition")
                        .IsRequired();
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ListFieldDefinition", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("SharedFieldRefs");

                    b.Navigation("SubFields");
                });

            modelBuilder.Entity("Collectary.Core.Domain.Fields.ListFieldValue", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
