<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="Bogus" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FakeItEasy" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Collectary.UI\Collectary.UI.csproj" />
    <ProjectReference Include="..\..\src\Collectary.Presentation\Collectary.Presentation.csproj" />
    <ProjectReference Include="..\..\src\Collectary.Infrastructure\Collectary.Infrastructure.csproj" />
  </ItemGroup>

</Project>
