<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Collectary.Search\Collectary.Search.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Collectary.Search.Avalonia.Tests" />
    <InternalsVisibleTo Include="Collectary.UI.Tests" />
  </ItemGroup>

</Project>
